[package]
name = "sharky-explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { version = "1.4.26", features = ["enable-glwindow"] }
fltk-theme = "0.7.2"
walkdir = "2.5.0"
